default:
  content:
    - name: "Enterprise Ready Dashboards"
      path: "./local"
      description: "Dashboard with drill downs."
      tag:
        - "Demo Content|Enterprise"
      url: "/enterprise/"