default:
  db:
    drv: !expr odbc::odbc()
    DSN: "SQL Server"
    
local:
  db:
    drv: !expr RSQLite::SQLite()
    db: ":memory:"
    
rsconnect:
  db:
    drv: !expr odbc::odbc()
    DSN: "Datawarehouse"
    
quickstart:
  db:
    drv: !expr RSQLite::SQLite()
    db: ":memory:"
